controller_manager:
  ros__parameters:
    update_rate: 100 #Hz

    # Gripper controller
    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - robotiq_85_left_knuckle_joint

    ur5_controller:
      type: effort_controllers/JointGroupEffortController
      joints:
        - shoulder_pan_joint

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    use_sim_time: true


ur5_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity

gripper_controller:
  ros__parameters:
    joints:
      - robotiq_85_left_knuckle_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.1
      goal_time: 0.0
      robotiq_85_left_knuckle_joint: { trajectory: 0.8, goal: 0.8 }

    gains:
      robotiq_85_left_knuckle_joint: {p: 0.0, i: 0.0, d: 0.0}  
    open_loop_control: true