controller_manager:
  ros__parameters:
    update_rate: 100 #Hz

    # Gripper controller
    gripper_controller:
      type: position_controllers/GripperActionController
      joint: robotiq_85_left_knuckle_joint
      gains:
        robotiq_85_left_knuckle_joint: {p: 1.0, i: 0.0, d: 0.0}  
      action_monitor_rate: 20 #50
      goal_tolerance: 0.01
      max_effort: 1 #100
      allow_stalling: false
      stall_velocity_threshold: 0.001 #0.00025
      stall_timeout: 1.0

    ur5_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - shoulder_pan_joint
        - shoulder_lift_joint
        - elbow_joint
        - wrist_1_joint
        - wrist_2_joint
        - wrist_3_joint
      publish_rate: 50
      write_op_modes:
        - shoulder_pan_joint
        - shoulder_lift_joint
        - elbow_joint
        - wrist_1_joint
        - wrist_2_joint
        - wrist_3_joint

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


ur5_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      elbow_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

gripper_controller:
  ros__parameters:
    joint: robotiq_85_left_knuckle_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
