controller_manager:
  ros__parameters:
    update_rate: 50 #Hz

    cartpole_controller:    
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


cartpole_controller:
  ros__parameters:
    joints:
        - slider_to_cart
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
        


