controller_manager:
  ros__parameters:
    update_rate: 100 #Hz

    # Gripper controller
    gripper_controller:
      type: position_controllers/GripperActionController
      joint: robotiq_85_left_knuckle_joint
      gains:
        robotiq_85_left_knuckle_joint: {p: 1.0, i: 0.0, d: 0.0}  
      action_monitor_rate: 20
      goal_tolerance: 0.01
      max_effort: 0.1
      stall_velocity_threshold: 0.25
      stall_timeout: 10.0

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


gripper_controller:
  ros__parameters:
    joint: robotiq_85_left_knuckle_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 2.0
    allow_partial_joints_goal: false


